#pragma config(Motor,  port1,           RMDrive,       tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
#pragma config(Motor,  port4,           MogoliftL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MogoliftR,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBDrive,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           RBDrive,       tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          LMDrive,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous()
{
	//if this auton does not work at competition, there is a back up blocker auton located on my github under the name "BotBlock"
  //note: this auton is done by time, so it is not the best. If you are looking at this in the future, I would highly recommend creating an auton that is sensor based
	//we're starting the drive early so that the bot won't flip when the mobile goal lift is moved
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 127;
  motor [RMDrive] = 127;
  wait1Msec(500);
  //mobile goal lift is set to 127 in order to raise it up for lift off
  motor [MogoliftL] = 127;
  motor [MogoliftR] = 127;
  wait1Msec(2000);
  //lift is lower while driving so that it can go around the mobile goal
  motor [MogoliftL] = -100;
  motor [MogoliftR] = -100;
  wait1Msec(1500);
  //LIFT OFF
  //mobile goal should be in lift at this point. This is where all drive stops and the mobile goal is picked up.
  //Biggest concern here is tipping
  motor [LBDrive] = 0;
  motor [LMDrive] = 0;
  motor [RBDrive] = 0;
  motor [RMDrive] = 0;
  motor [MogoliftL] = 20;
  motor [MogoliftR] = 20;
  wait1Msec(150);
  //drive starts to go backwards with the mobile goal. Next task is dropping off the mobile goal
  motor [LBDrive] = -127;
  motor [LMDrive] = -127;
  motor [RBDrive] = -127;
  motor [RMDrive] = -127;
  wait1Msec(3000);
  //gradually turning left so that we can drop off the mobile goal... step one of 3 point turn
  motor [LBDrive] = -63;
  motor [LMDrive] = -63;
  motor [RBDrive] = -127;
  motor [RMDrive] = -127;
  wait1Msec(2000);
  // step 2 of 3 point turn
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 100;
  motor [RMDrive] = 100;
  wait1Msec(2000);
  // step 3 of 3 point turn
  // going over the pipe hopefully
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 127;
  motor [RMDrive] = 127;
  wait1Msec(500);
  //slow down and lower lift so we can shake out mobile goal
  motor [LBDrive] = 63;
  motor [LMDrive] = 63;
  motor [RBDrive] = 63;
  motor [RMDrive] = 63;
  motor [MogoliftL] = 10;
  motor [MogoliftR] = 10;
  wait1Msec(400);
  //TIME TO SHAKE VIGOROUSLY
  motor [LBDrive] = -127;
  motor [LMDrive] = -127;
  motor [RBDrive] = -127;
  motor [RMDrive] = -127;
  wait1Msec(5);
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 127;
  motor [RMDrive] = 127;
  wait1Msec(5);
  motor [LBDrive] = -127;
  motor [LMDrive] = -127;
  motor [RBDrive] = -127;
  motor [RMDrive] = -127;
  // at this point, the mobile goal should be off of the lift. Now we just have to go park in the square.
  wait1Msec(200);
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 100;
  motor [RMDrive] = 100;
  wait1Msec(2000);
  motor [LBDrive] = -63;
  motor [LMDrive] = -63;
  motor [RBDrive] = -127;
  motor [RMDrive] = -127;
  wait1Msec(2000);
  motor [LBDrive] = 127;
  motor [LMDrive] = 127;
  motor [RBDrive] = 127;
  motor [RMDrive] = 127;
  wait1Msec(300);
  motor [LBDrive] = 0;
  motor [LMDrive] = 0;
  motor [RBDrive] = 0;
  motor [RMDrive] = 0;
  // auton should be done, and we should be parked
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {

		motor[LBDrive]  = (vexRT[Ch1] + vexRT[Ch3]);
		motor[RBDrive]  = (vexRT[Ch1] - vexRT[Ch3]);
		motor[LMDrive]  = (vexRT[Ch1] + vexRT[Ch3]);
		motor[RMDrive]  = (vexRT[Ch1] - vexRT[Ch3]);


if (vexRT[Btn6U] == 1)
		{
			motor[MogoliftL] = 127;
			motor[MogoliftR] = 127;
		}
else if (vexRT[Btn6D] == 1)
		{
			motor[MogoliftL] = -127;
			motor[MogoliftR] = -127;
		}
else
	  {
	  	motor[MogoliftL] = 0;
			motor[MogoliftR] = 0;
	  }
    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
